config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources "categories"
  resources "image_details"
  resources "sections"
  resources "authors"
  resources "articles"
  root "welcome#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  has_one :article_content, :dependent => :destroy
  has_and_belongs_to_many :categories
  belongs_to :author
  belongs_to :section
  belongs_to :image

end

app/models/article_content.rb
class ArticleContent < ApplicationRecord

  belongs_to :article

end

app/models/author.rb
class Author < ApplicationRecord

  validates :fullname,:firstname, presence: true, format: { with: /\A([-a-zA-Z_ ]+|)\z/i, message: "only allows letters" }
  validates :fullname,:firstname , uniqueness: true
  validates :email, presence: true, uniqueness: true , format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i , message: "Please provide valid email"}
  has_many :articles

  scope :by_active, -> { where("active = ?",true)}

end

app/models/category.rb
class Category < ApplicationRecord

  validates :name,:alias_name, presence: true, format: { with: /\A([-a-zA-Z_ ]+|)\z/i, message: "only allows letters" }

  has_and_belongs_to_many :articles

  #scope :parent, ->(category) { where("parent_id = ?",category.parent_id)}
end

app/models/image.rb
class Image < ApplicationRecord

  has_many :articles
  has_many :image_details

end

app/models/image_detail.rb
class ImageDetail < ApplicationRecord

  belongs_to :image

end

app/models/section.rb
class Section < ApplicationRecord

  validates :name,:alias_name, presence: true, format: { with: /\A([-a-zA-Z_ ]+|)\z/i, message: "only allows letters" }

  has_many :articles

  scope :by_active, -> { where("active = ?",true)}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  def new
   @article = Article.new
  end

  def edit

  end

  def create

  end

  def show

  end

  def index

  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def new
  @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:notice] = "Author is created Successfully"
      redirect_to authors_path
    else
      logger.info"==========#{@author.errors.messages}"
      render 'new'
    end
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to authors_path
    else
      render 'edit'
    end
  end
  def edit
    @author = Author.find_by_id(params[:id])
  end

  def show
    @author = Author.find_by_id(params[:id])
  end

  def index
    @authors = Author.all
    if @authors.blank?
      flash[:notice] = "No Authors were Created"
    end
  end

  private
  def author_params
    params.require(:author).permit(:firstname, :lastname, :email, :active, :fullname)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
   @category = Category.new
  end
  def create
    @category = Category.new(category_params)
    if @category.save
      render 'index'
    else
      logger.info"==========#{@category.errors.messages}"
      render 'new'
    end
  end
  def update
    @category = Category.find(params[:id])
    if @category.id != params[:category][:parent_id].to_i
     if @category.update(category_params)
      redirect_to categories_path
     else
      render 'edit'
     end
    else
      render 'edit'
    end
  end
  def edit
    @category = Category.find_by_id(params[:id])
  end

  def show
    @category = Category.find_by_id(params[:id])
  end

  def index
    @categories = Category.all
    if @categories.blank?
      flash[:notice] = "No Categories were Created"
    end
  end
  private
  def category_params
    params.require(:category).permit(:name, :alias_name, :parent_id, :active)
  end
end

app/controllers/image_details_controller.rb
class ImageDetailsController < ApplicationController

  def new

  end

  def edit

  end

  def show

  end

  def index

  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  def new
    @section = Section.new
  end

  def create
   @section = Section.new(section_params)
   if @section.save
     flash[:notice] = "Section is created Successfully"
      redirect_to sections_path
   else
     logger.info"==========#{@section.errors.messages}"
     render 'new'
   end
  end

  def update
    @section = Section.find(params[:id])

    if @section.update(section_params)
      redirect_to sections_path
    else
      render 'edit'
    end
  end
  def edit
    @section = Section.find_by_id(params[:id])
  end

  def show
    @section = Section.find_by_id(params[:id])
  end

  def index
   @sections = Section.all
   if @sections.blank?
     flash[:notice] = "No Sections were Created"
   end
  end

  private
  def section_params
    params.require(:section).permit(:name, :alias_name, :active)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def custom_autocomplete(name, search_obj, field, populate_obj)
    search_data=search_obj.collect{|x| {:name=>eval("x."+field), :id=>x.id}}.to_json
    prepopulate=populate_obj.collect{|x| {:name=>eval("x."+field), :id=>x.id}}.to_json
    id=name.gsub('[', '_').chop.gsub(']', '_').chop

    auto_complete="<input type='text' id='#{id}'/>
    <script type='text/javascript'>
        $(document).ready(function() {
             $('##{id}').tokenInput(#{search_data}, {
             prePopulate: #{prepopulate},
             preventDuplicates: true,
             tokenName:'#{name}[]',
            });
        });
    </script>"

    auto_complete
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/image_details_helper.rb
module ImageDetailsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article ,html: {class: "form-horizontal"} do |f| %>
    <div class="form-group">
      <div class="col-sm-12 col-xs-12">
        <div class="col-sm-6">
          <label class="control-label col-sm-4" for="name">Title :</label>
          <div class="col-sm-8 col-xs-12">
            <%= f.text_field :title ,:placeholder => 'Title',class:"form-control"%>
          </div>
        </div>
        <div class="col-sm-6" >
          <label class="control-label col-sm-4" for="name">Sub Title:</label>
          <div class="col-sm-8 col-xs-12">
            <%= f.text_field :sub_title,:placeholder => 'Sub Title',class:"form-control"%>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12 col-xs-12">
        <div class="col-sm-6 col-xs-12">
          <label class="control-label col-sm-4" for="name">Article Type :</label>
          <div class="col-sm-8 col-xs-12">
            <%= f.collection_select(:section_id , Section.order("name asc"),:id,:name,{:include_blank => "Please Select Article Type" })%>
          </div>
          </div>
        <div class="col-sm-6 col-xs-12">
          <label class="control-label col-sm-4" for="name">Author :</label>
          <div class="col-sm-8 col-xs-12">
            <%= f.collection_select(:author_id , Author.order("firstname asc"),:id,:firstname,{:include_blank => "Please Select The Author" })%>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12 col-xs-12">
        <div class="col-sm-6">
          <label class="control-label col-sm-4" for="pwd">Categories :</label>
          <div class="col-sm-8 col-xs-12">
            <%#= f.text_field : ,class:"form-control"%>
            <%= raw custom_autocomplete("article[category_ids]", Category.all, "name", @article.categories) %>
           </div>
        </div>
        <div class="col-sm-6" >
          <label class="control-label col-sm-4" for="name">Publish Date :</label>
          <div class="col-sm-8 col-xs-12">
            <%#= f.datetime_select :expiry_date,class:"form-control"%>
            <%= f.text_field :publish_date, {:class => "form-control" ,:placeholder => 'Publish Date', id: 'display-date'} %>
            <div id="display-date-field"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12 col-xs-12">
        <div class="col-sm-6">
          <label class="control-label col-sm-4" for="pwd">Expiry Date :</label>
          <div class="col-sm-8 col-xs-12">
            <%= f.text_field :expiry_date, {:class => "form-control" ,:placeholder => 'Expiry Date', id: 'expiry-date'} %>
            <div id="expiry-date-field"></div>
            <%#= f.datetime_select :publish_date ,class:"form-control"%>
          </div>
        </div>
        <div class="col-sm-6" >
         <label class="control-label col-sm-4" for="name">Status :</label>
          <div class="col-sm-8 col-xs-12">
            <%#= f.text_field :expiry_date,class:"form-control"%>
            <label class="switch">
              <input type="checkbox">
              <div class="slider round"></div>
            </label>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12">
       <%= f.text_area :description, class: "tinymce", :rows => 40, :cols => 120 %>
      </div>
    </div>
<% end %>


<script>
  $('#display-date-field').calendar({
    trigger: '#display-date',
    zIndex: 999,
    onSelected: function (view, date, data) {
      console.log('event: onSelected')
    },
    onClose: function (view, date, data) {
      console.log('event: onClose');
      console.log('view:' + view);
      console.log('date:' + date);
      console.log('data:' + (data || 'None'));
    }
  });



</script>

app/views/articles/edit.html.erb
<div class="article_block col-md-12 col-sm-12 col-xs-12 no-padding">
  <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">Edit Article</a></h3>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
 <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">All Articles</a></h3>
    </div>
  </div>

app/views/articles/new.html.erb
<div class="article_block col-md-12 col-sm-12 col-xs-12 no-padding">
  <div class="container no-padding">
    <div class="row no-margin">
      <%= tinymce_assets %>
      <h3 class="under"><a href="#nogo">New Article</a></h3>
      <%= render :partial => 'form' %>
    </div>
  </div>
</div>


<%= tinymce :plugins => ["wordcount", "paste", "preview", "code", "table", "searchreplace", "image"], :toolbar => ["formatselect | searchreplace undo redo | bullist numlist | code image"] %>

app/views/articles/show.html.erb
<div class="article_block col-md-12 col-sm-12 col-xs-12 no-padding">
  <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">Show Article</a></h3>
    </div>
  </div>
</div>

app/views/authors/_form.html.erb
<div class="container">

    <%= form_for @author ,html: {class: "form-horizontal"} do |f| %>

      <div class="form-group">
      <% if @author.errors.any? %>
          <div class="alert alert-danger fade in col-sm-4">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <h6>
              <strong>Danger!</strong> <%= pluralize(@author.errors.count, "error") %> prohibited
              this article from being saved:
            </h6>
            <ul>
              <% @author.errors.full_messages.each do |msg| %>
                  <h6><li><%= msg %></li></h6>
              <% end %>
            </ul>
          </div>
      <% end %>
      </div>
    <div class="form-group">
      <div class="col-sm-12">
       <div class="col-sm-6">
      <h4><label class="control-label col-sm-4" for="name">First name :</label></h4>
      <div class="col-sm-8 col-xs-12">
        <%= f.text_field :firstname ,class:"form-control"%>
      </div>
    </div>
      <div class="col-sm-6" >
      <h4><label class="control-label col-sm-4" for="name">Last Name :</label></h4>
      <div class="col-sm-8 col-xs-12">
        <%= f.text_field :lastname,class:"form-control"%>
      </div>
       </div>
    </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12">
        <div class="col-sm-6">
          <h4><label class="control-label col-sm-4" for="pwd">Full Name :</label></h4>
          <div class="col-sm-8 col-xs-12">
          <%= f.text_field :fullname ,class:"form-control"%>
        </div>
          </div>
         <div class="col-sm-6" >
           <h4><label class="control-label col-sm-4" for="name">Email :</label></h4>
            <div class="col-sm-8 col-xs-12">
              <%= f.text_field :email,class:"form-control"%>
            </div>
          </div>
        </div>
      </div>
    <div class="form-group">
          <h4><label class="control-label col-sm-2 " >Active :</label></h4>
      <div class="col-sm-8">
          <%= f.check_box :active , class:"check_box" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-10">
        <%= f.submit 'Submit', :class => "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/authors/edit.html.erb
 <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">Edit Author</a></h3>
      <%= render :partial => "form" %>
    </div>
  </div>

app/views/authors/index.html.erb
 <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">All Authors</a></h3>
    </div>
   <% if flash[:notice] %>
       <div class="alert alert-success fade in">
         <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
         <h5><strong>Info!</strong> <%= flash[:notice] if flash[:notice]%></h5>
       </div>
   <% end %>
   <% if !@authors.blank? %>
       <% @authors.each do |author| %>
           <div class="container col-sm-4">
             <div class="row">
               <button type="button" class="btn btn-info"><h2 class="under"><a href="#nogo"><%=link_to author.fullname ,edit_author_path(author)%></a></h2></button>
             </div>
           </div>
       <% end %>

 <% end %>
  </div>

app/views/authors/new.html.erb
 <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">New Author</a></h3>
      <%= render :partial => "form" %>
    </div>
  </div>

app/views/authors/show.html.erb
 <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">Show Author</a></h3>
    </div>
  </div>

app/views/categories/_form.html.erb
<div class="container">

    <%= form_for @category ,html: {class: "form-horizontal"} do |f| %>

      <div class="form-group">
      <% if @category.errors.any? %>
          <div class="alert alert-danger fade in col-sm-4">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <h6>
              <strong>Danger!</strong> <%= pluralize(@category.errors.count, "error") %> prohibited
              this article from being saved:
            </h6>
            <ul>
              <% @category.errors.full_messages.each do |msg| %>
                  <h6><li><%= msg %></li></h6>
              <% end %>
            </ul>
          </div>
      <% end %>
      </div>
    <div class="form-group">
      <div class="col-sm-12">
       <div class="col-sm-6">
     <label class="control-label col-sm-4" for="name">Name :</label>
      <div class="col-sm-8 col-xs-12">
        <%= f.text_field :name ,class:"form-control"%>
      </div>
    </div>
      <div class="col-sm-6" >
     <label class="control-label col-sm-4" for="name">Alias Name :</label>
      <div class="col-sm-8 col-xs-12">
        <%= f.text_field :alias_name,class:"form-control"%>
      </div>
       </div>
    </div>
    </div>
    <div class="form-group">
      <div class="col-sm-12">
        <div class="col-sm-6">
          <label class="control-label col-sm-4" for="pwd">Parent Name :</label>
          <div class="col-sm-8 col-xs-12">
          <%= f.collection_select(:parent_id ,Category.all,:id,:alias_name,{:include_blank => "For Creating Subcategory" })%>
        </div>
          </div>
         <div class="col-sm-6" >
           <label class="control-label col-sm-4 " >Active :</label>
           <div class="col-sm-1 col-xs-12">
             <%= f.check_box :active , class:"check_box" %>
           </div>
          </div>
        </div>
      </div>

    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-10">
        <%= f.submit 'Submit', :class => "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
 <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">Edit Category</a></h3>

      <%= render :partial => "form" %>
    </div>
  </div>

app/views/categories/index.html.erb
 <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">All Categories</a></h3>
    </div>
   <% if flash[:notice] %>
       <div class="alert alert-success fade in">
         <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
         <h5><strong>Info!</strong> <%= flash[:notice] if flash[:notice]%></h5>
       </div>
   <% end %>
   <% if !@categories.blank? %>

           <div class="container row">
             <% @categories.each do |category| %>
             <div class="col-sm-4">
              <%= link_to category.name ,edit_category_path(category) ,class:"btn btn-info"%>
             </div>
             <% end %>
           </div>
 <% end %>
  </div>

app/views/categories/new.html.erb
 <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">New Category</a></h3>
      <%= render :partial => "form" %>
    </div>
  </div>

app/views/categories/show.html.erb
 <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">Show Category</a></h3>
    </div>
  </div>

app/views/image_details/edit.html.erb
<div class="article_block col-md-12 col-sm-12 col-xs-12 no-padding">
  <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">Edit Image</a></h3>
    </div>
  </div>
</div>

app/views/image_details/index.html.erb
<div class="article_block col-md-12 col-sm-12 col-xs-12 no-padding">
  <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">All Images</a></h3>
    </div>
  </div>
</div>

app/views/image_details/new.html.erb
<div class="article_block col-md-12 col-sm-12 col-xs-12 no-padding">
  <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">New Image</a></h3>
    </div>
  </div>
</div>

app/views/image_details/show.html.erb
<div class="article_block col-md-12 col-sm-12 col-xs-12 no-padding">
  <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">Show Image</a></h3>
    </div>
  </div>
</div>

app/views/sections/_form.html.erb
<div class="container">

    <%= form_for @section ,html: {class: "form-horizontal"} do |f| %>

      <div class="form-group">
      <% if @section.errors.any? %>
          <div class="alert alert-danger fade in col-sm-4">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <h6>
              <strong>Danger!</strong> <%= pluralize(@section.errors.count, "error") %> prohibited
              this article from being saved:
            </h6>
            <ul>
              <% @section.errors.full_messages.each do |msg| %>
                  <h6><li><%= msg %></li></h6>
              <% end %>
            </ul>
          </div>
      <% end %>
      </div>
    <div class="form-group">
      <h4><label class="control-label col-sm-4" for="name">Name :</label></h4>
      <div class="col-sm-4 col-xs-12">
        <%= f.text_field :name ,class:"form-control"%>
      </div>
    </div>
    <div class="form-group">
      <h4><label class="control-label col-sm-4" for="pwd">Alias Name :</label></h4>
      <div class="col-sm-4">
        <%= f.text_field :alias_name ,class:"form-control"%>
      </div>
    </div>
    <div class="form-group">
          <h4><label class="control-label col-sm-4 " >Active :</label></h4>
      <div class="col-sm-4">
          <%= f.check_box :active , class:"check_box" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-4 col-sm-10">
        <%= f.submit 'Submit', :class => "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/sections/edit.html.erb
 <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">Edit Section</a></h3>
      <%= render :partial => "form" %>
    </div>
  </div>

app/views/sections/index.html.erb
 <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">All Sections</a></h3>
    </div>
   <% if flash[:notice] %>
       <div class="alert alert-success fade in">
         <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
         <h5><strong>Info!</strong> <%= flash[:notice] if flash[:notice]%></h5>
       </div>
   <% end %>
   <% if !@sections.blank? %>
   <% @sections.each do |section| %>
     <div class="container col-sm-4">
    <div class="row">
      <button type="button" class="btn btn-info"><h2 class="under"><a href="#nogo"><%= link_to section.name ,edit_section_path(section) %></a></h2></button>
    </div>
   </div>
   <% end %>
   <% end %>
  </div>

app/views/sections/new.html.erb
 <div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">New Section</a></h3>
      <%= render :partial => "form" %>
    </div>
  </div>

app/views/sections/show.html.erb
<div class="container no-padding">
    <div class="row no-margin">
      <h3 class="under"><a href="#nogo">Show Section</a></h3>
    </div>
  </div>